export BW_MASTER=$(cat ~/.local/share/bitwarden/key)
export BW_EMAIL=$(cat ~/.local/share/bitwarden/email)
export BW_CLIENTID=$(cat ~/.local/share/bitwarden/clientid)
export BW_CLIENTSECRET=$(cat ~/.local/share/bitwarden/clientsecret)
export BW_SESSION=$(bw login --raw $BW_EMAIL $BW_MASTER)
#export BW_SESSION="$(bw unlock $BW_MASTER 2>/dev/null | grep 'export' | sed -E 's/.*export BW_SESSION="(.*==)"$/\1/')"
