#!/bin/sh

# this file runs when a DM logs into a graphical sessions.
# If you use startx/xinit , this file will also be sourced.

# nitrogen --restore &
# deadd-notification-center &
dwmblocks &
mopidy &
nm-applet &
pulsedaemondwmb &
transmission-daemon &
setbg &
xcompmgr &
remaps &
dunst &
caffeine &
dropbox &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#volumeicon &
#xrdb ${XDG_CONFIG_HOME:$HOME/.config}/x11/xresources & # Uncomment to user Xresources color/settings on startup 
# blueman-applet &
# udiskie -s &
# xdman &
