#!/bin/sh

# this file runs when a DM logs into a graphical sessions.
# If you use startx/xinit , this file will also be sourced.

# nitrogen --restore &
# deadd-notification-center &
mopidy &
nm-applet &
dwmblocks &
pulsedaemondwmb &
setbg &
xcompmgr &
#volumeicon &
#xrdb ${XDG_CONFIG_HOME:$HOME/.config}/x11/xresources & # Uncomment to user Xresources color/settings on startup 
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# blueman-applet &
# udiskie -s &
remaps &
dunst &
# caffeine &
# xdman &
# dropbox &
