#!/bin/sh

# this file runs when a DM logs into a graphical sessions.
# If you use startx/xinit , this file will also be sourced.

nitrogen --restore &
deadd-notification-center &
nm-applet &
dwmblocks &
setbg &
xcompmgr &
#volumeicon &
#xrdb ${XDG_CONFIG_HOME:$HOME/.config}/x11/xresources & # Uncomment to user Xresources color/settings on startup 
blueman-applet &
udiskie -s &
remaps &
dunst &
dropbox &
