require ('plugins')
require ('globals')
require ('colorscheme')
vim.cmd('source ~/.config/nvim/vimscripts/func.vim')
require ('settings')
require ('keymaps')
-- vim.cmd('source ~/.config/nvim/vimscripts/whichkey/init.vim')
-- Plugin
require ('lsp')
require ('qs-whichkey')
require ('qs-specs')
require ('qs-autopairs')
require ('qs-compe')
require ('qs-galaxyline')
require ('qs-lspsaga')
require ('qs-treesitter')
require ('qs-comment')
require ('qs-colorizer')
require ('qs-startify')
require ('qs-telescope')
require ('qs-nvimtree')
require ('qs-gitsigns')
require ('qs-gitblame')
require ('qs-indentline')
require ('qs-hop')
require ('qs-quickscope')
require ('qs-bookmarks')
-- require ('qs-barbar')
require ('qs-lf')
require ('qs-vsnip')
require ('qs-toggleterm')
require ('qs-lightbulb')
require ('qs-peekup')
require ('qs-neuron')
require ('qs-truezen')
-- vimscripts
-- vim.cmd('source ~/.config/nvim/vimscripts/wiki.vim')
vim.cmd('source ~/.config/nvim/vimscripts/autocmd.vim')
-- vim.cmd('source ~/.config/nvim/vimscripts/lf.vim')
-- vim.cmd('source ~/.config/nvim/vimscripts/notes.vim')
vim.cmd('source ~/.config/nvim/vimscripts/orgmode.vim')
-- COMPTACH = require'lsp'.common_on_attach
-- LSP
-- Completions Idk if 2 of them on will have an effects
-- require ('qs-compe')
-- require ('qs-completions')
-- Language
require ('lsp.virtual_text')
require ('lsp.clangd-lsp')
require ('lsp.rust-lsp')
require ('lsp.bash-lsp')
require ('lsp.lua-lsp')
require ('lsp.vim-lsp')
require ('lsp.python-lsp')
require ('lsp.docker-lsp')

require ('lsp.json-lsp')
require ('lsp.yaml-lsp')

require ('lsp.html-lsp')
require ('lsp.css-lsp')
require ('lsp.js-ts-lsp')
require ('lsp.latex-lsp')
require ('lsp.ruby-lsp')
require ('lsp.php-lsp')
-- require ('lsp.swift-lsp')
require ('lsp.go-lsp')
