require ('plugins')
require ('colorscheme')
require ('settings')
require ('keymaps')
require ('qs-specs')
-- Plugin
require ('lsp')
require ('qs-galaxyline')
require ('qs-lspsaga')
require ('qs-treesitter')
require ('qs-comment')
require ('qs-startify')
require ('qs-colorizer')
require ('qs-telescope')
require ('qs-nvimtree')
require ('qs-gitsigns')
require ('qs-indentline')
require ('qs-hop')
require ('qs-quickscope')
require ('qs-bookmarks')

-- vimscripts
vim.cmd('source ~/.config/nvim/vimscripts/whichkey/init.vim')
vim.cmd('source ~/.config/nvim/vimscripts/wiki.vim')
vim.cmd('source ~/.config/nvim/vimscripts/autocmd.vim')
vim.cmd('source ~/.config/nvim/vimscripts/lf.vim')

vim.cmd('source ~/.config/nvim/vimscripts/func.vim')
